AWSTemplateFormatVersion: 2010-09-09
Description: >-
  iot-siginage-event-batch
Transform:
- AWS::Serverless-2016-10-31

Resources:
  PublishMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PublishSignageMessageFunction
      Description: "A Lambda function that publishes a message to an IoT topic every 5 minutes" 
      Runtime: python3.12
      Architectures:
      - arm64
      CodeUri: src/handlers/
      Handler: publish_message.handler
      Role: !GetAtt FunctionRole.Arn
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/30 * * * ? *)
      Environment:
        Variables:
          TARGET_CITY: 'Nagoya,JP'
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSIoTPublish
  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PublishMessageFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - iot:Publish
                Resource: "*"
        - PolicyName: ReatParameterStorePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource: "*"
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: true
