on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }} 
      - name: Setup SAM
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build SAM
        run: sam build --use-container
      - name: Deploy SAM
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
